repositories:
  - "dentist-project-prod" 
main_vpc:
   # should be created in console, then add the id here 
  prod_aws_eips :
      prod-server-01: "eipalloc-0207bd645a5637dd7" 
      
  cidr  : "10.0.0.0/16"
  environment: 
    prod:
      elb:
        name: "front-lb"
        type: "application"
        enable_deletion: false
        env: "prod"
        target_group:
            name         : "application-front"
            port         : 80
            protocol     : "HTTP"
        listeners:
            type         : "forward"
            port         : 80
            protocol     : "HTTP"
      ec2:
        prod-server-01:
          amount: 1
          ami: "ami-007855ac798b5175e"
          type: "t2.micro"
          env: "prod"
          key_name: "dentist-project-prod-key"
        prod-server-02:
          amount: 1
          ami: "ami-007855ac798b5175e"
          type: "t2.micro"
          env: "prod"
          key_name: "dentist-project-prod-key"
      rds :
        prod-db-postgres:
          env: "prod"
          db_name: "mydatabase"       
          db_username: "postgres"        
          db_password: "postgres"     
          allocated_storage: 20       
          engine: "postgres"
          engine_version: "14.4"        
          instance_class: "db.t2.micro"
          skip_final_snapshot: false

                

          
